# Permalinks
permalink:        pretty

# Setup
title:            Keebs
tagline:          "Guides and notes on mechanical keyboard building"
description:      "Guides and notes on mechanical keyboard building"
url:              http://keebs.mike.gg
baseurl:          "http://keebs.mike.gg/"

author:
  name:           'Mike'
  url:            http://keebs.mike.gg

paginate:         5
